goodchai0/day-planner

script.js

Hi @goodchai0 , I discovered an **issue when user hit 'Enter' key on input field then page is getting refreshed**. I've resolved this issue now. Can you please review and accept my pull request.

Page was getting refreshed when we hit enter in input box

---

style.css

Added bg image that will change on each refresh.

Added background image

---

index.html
script.js

Hello There,
I have added dark mode to the website and softened some colours so that they are easier on the eye.
Thank You.

Added dark mode and made some minor changes

---

index.html
style.css

i have doe some changes regarding CSS please merge it  .

changed some CSS

---

script.js

The color is according to the color of the sky at that time.

Changed the colour of boxes

---

script.js
style.css

Responsiveness in this application for mobile view has been improved. If further changes is needed please comment on it

Fixed Issue #18

---

script.js

This fix the console error
closes #50

Fix console error

---

README.md

Remove the `- It run's on the port 5500 on your local machine`in reade, as there isn't any service running on localhost 5500

Remove wrong information of readme.md

---

.vscode/settings.json
style.css

animated buttons

---

index.html

I have added a scroll to the top button code.
It closes issue #54

regarding issue #54

---

CONTRIBUTORS.md
README.md

added a few lines to the readme and made some correction to typo errors

Updated the readme

---

index.html

I added titles to the buttons and links to make it easier to understand

Added title to buttons and nav-links

---

index.html

fixed the bottom button in navbar

---

index.html

Made some changes in footer social media icons

modified social media icons in footer

---

script.js

Hi @goodchai0 
Have made the changes to fix the issue for deletion where every time the last element was getting deleted instead of the selected element
Can you please review the pr
Issue link:- https://github.com/goodchai0/day-planner/issues/31
Screencast for the changes
https://www.loom.com/share/de4dc2f74616499fa1be3f9475f00730

Fix task deletion

---

index.html
style.css

fixed 'back to top' button

---

script.js

Please check my PR. If you want any changes, do let me know.

Added Enter Functionality

---

day_planner_next js/pages/index.js

Fixed some issues for hosting and added local storage instead of cookies

---

day_planner_next js/README.md
day_planner_next js/pages/index.js

Added readme.md in day_planner_next js folder in detail explanation about the project and how to run it.

added detail explanation about the project and how to run it.

---

style.css

Delete button text "Delete" was not visible due to bad styling.
Test locally by running live server
Before:
After:

Fix: Delete Button styles

---

index.html

Fixing UI on banner and footer - add margin for eye catching
- [✓] Bug fix (non-breaking change which fixes an issue)
already test on local computer
- [✓] I have read the [Contributing Guidelines](https://github.com/goodchai0/day-planner/blob/master/CONTRIBUTING.md)?

fixing a couple margin on banner and footer

---

day-planner-master/index.html
day-planner-master/style.css

In the light theme, the text on the button was not visible so I changed the color of the button now it works fine.

updated back to top button
